# permissions for end users to edit netests.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: netest-editor-role
rules:
- apiGroups:
  - netest.terloo.github.com
  resources:
  - netests
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - netest.terloo.github.com
  resources:
  - netests/status
  verbs:
  - get
