---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - netest.terloo.github.com
  resources:
  - netests
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - netest.terloo.github.com
  resources:
  - netests/finalizers
  verbs:
  - update
- apiGroups:
  - netest.terloo.github.com
  resources:
  - netests/status
  verbs:
  - get
  - patch
  - update
